# Site settings
title: "Yaşam Desteği Vakfı"
name: "Yaşam Desteği Vakfı"
description: "Life Support Foundation Trust - Yaşam Desteği Vakfı"
baseurl: ""
url: "https://yasamdestegivakfi.github.io"
lang: "tr"
locale: "tr_TR"
timezone: "Europe/Istanbul"

# Author information
author:
  name: "Yaşam Desteği Vakfı"
  email: "info@yasamdestegivakfi.org"

# Social media
social:
  github: yasamdestegivakfi

# Site variables
site_name: "Yaşam Desteği Vakfı"
site_description: "Life Support Foundation Trust - Yaşam Desteği Vakfı"
site_url: "https://yasamdestegivakfi.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: jekyll-theme-primer

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-github-metadata

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - .gitignore
